version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      micronaut:
        patterns:
          - "io.micronaut*"
      testing:
        patterns:
          - "org.junit*"
          - "org.mockito*"
          - "org.assertj*"
          - "org.testcontainers*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
