pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'candidate-manager'

include 'api'
include 'application'
include 'domain'
include 'infrastructure'
